version: '3.9'

services:
  frontend:
    build:
      context: ./envacare_project_frontend
    container_name: frontend_app
    depends_on:
      - backend
    env_file:
      - ./envacare_project_frontend/.env
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_PORT=8501